apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      containers:
        - name: student-api
          image: student-management-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/mahasiswa_db
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-management
spec:
  type: NodePort
  selector:
    app: student-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
