apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: student-management
type: Opaque
stringData:
  POSTGRES_DB: mahasiswa_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
